version: 1.0.{build}
configuration: Debug
platform: Any CPU

before_build:
- cmd: nuget restore

build:
  project: HandyTools.sln
  verbosity: minimal
  
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: handytools-bot
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true