version: 1.0.{build}
configuration: Debug
platform: Any CPU
clone_folder: c:\projects\handytools

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node
  # install modules
  - cmd: cd c:\projects\handytools\HandyTools.Web
  - cmd: npm install
  - cmd: cd ..
  
# Post-install test scripts.
# test_script:
#   # Output useful info for debugging.
#   - node --version
#   - npm --version

build:
  project: HandyTools.sln
  verbosity: normal
 
before_build:
  - cmd: nuget restore -SolutionDirectory c:\projects\handytools

branches:
#Whitelist
    only:
        - master

# Don't actually build.
# build: off
       
artifacts:
  - path: HandyTools.Web\
    name: handytoolsweb     
    type: zip  
  - path: HandyTools.Web.API\
    name: handytoolsapi  
    type: zip
    
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.gatech.edu/gt-omscs-dbscd/CS6400Spring16Team60.git`n"
  - git config --global user.email "find.leonardo@gmail.com"
  - git config --global user.name "lperez42"
  - git remote rename origin upstream
  - git remote add gatech https://github.gatech.edu/gt-omscs-dbscd/CS6400Spring16Team60.git
  - git checkout master
  - git pull gatech master
  - git push gatech master
  
after_build:
  appveyor PushArtifact <zip_path> -DeploymentName handytoolsweb

deploy:
  provider: Environment
  name: HandyToolsWeb
  provider: Environment
  name: HandyToolsWebApi

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: handytools-bot
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true