version: 1.0.{build}
configuration: Debug
platform: Any CPU

before_build:
- cmd: nuget restore

build:
    project: HandyTools.sln
    verbosity: minimal
 
branches:
#Whitelist
    only:
        - master
       
environment:
    access_token:
        secure: ZQQ+zSR7as/HV8jDAzoCGcyckNahNpFZ97J+CNiHGZeQrkNWvLPyZWVBeaxzUvJv 

deploy:
- provider: S3
  access_key_id: AKIAJ5FDT2D2WPEZIUMA
  secret_access_key:
    secure: vQsAdbQEVkppDmyU+reBBPHL4zSKb7N2R1mHiO964YuWFvB0yOY3y3M5pTc+B++h
  region: us-east-1
  bucket: handytools
  artifacts: handytoolsweb
  set_public: true
- provider: S3
  access_key_id: AKIAJ5FDT2D2WPEZIUMA
  secret_access_key:
    secure: vQsAdbQEVkppDmyU+reBBPHL4zSKb7N2R1mHiO964YuWFvB0yOY3y3M5pTc+B++h
  region: us-east-1
  bucket: handytools-api
  artifacts: handytoolswebapi
  set_public: true
    
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.gatech.edu/gt-omscs-dbscd/CS6400Spring16Team60.git`n"
  - git config --global user.email "find.leonardo@gmail.com"
  - git config --global user.name "lperez42"
  - git remote rename origin upstream
  - git remote add gatech https://github.gatech.edu/gt-omscs-dbscd/CS6400Spring16Team60.git
  - git checkout master
  - git pull gatech master
  - git push gatech master
  
after_build:
  - ps: $root = Resolve-Path .\HandyTools.Web; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -DeploymentName handytoolsweb }
  - ps: $root = Resolve-Path .\HandyTools.Web.API; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -DeploymentName handytoolswebapi }

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: handytools-bot
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true