  - git push gatech master 
   
after_build: 
  - ps: $root = Resolve-Path .\HandyTools.Web; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_) -DeploymentName handytoolsweb } 
  - ps: $root = Resolve-Path .\HandyTools.Web.API; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_) -DeploymentName handytoolswebapi } 
  - ps: $root = Resolve-Path .\HandyTools.Web; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ ) -DeploymentName handytoolsweb } 
  - ps: $root = Resolve-Path .\HandyTools.Web.API; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ ) -DeploymentName handytoolswebapi } 
 
notifications: 
- provider: Slack 
Clean PS command.

Leonardo Perez
authored3/31/2016 @ 1:36 AM
commit:c4e057
parent:cdd421
0 added
0 deleted
1 modified
appveyor.yml
File History: appveyor.yml
Diff View
File View
Show blame details
Clean PS command.
6 minutes ago by Leonardo Perez
c4e057
Testing deployment.
25 minutes ago by Leonardo Perez
cdd421
Another one.
an hour ago by Leonardo Perez
cadfc3
Updated deployment to S3 config.
2 hours ago by Leonardo Perez
76aeea
Added after_build configuration.
2 hours ago by Leonardo Perez
2bcf0f
Another fix.
3 hours ago by Leonardo Perez
9d485f
Fixed spacing.
3 hours ago by Leonardo Perez
9f49ed
Added deployment to S3 configuration.
3 hours ago by Leonardo Perez
ab50d3
Reverted test changes.
3 hours ago by Leonardo Perez
d76827
Commented pulls.
3 hours ago by Leonardo Perez
f9c84a
Added specific pull.
4 hours ago by Leonardo Perez
7a31e0
Added oauth.
4 hours ago by Leonardo Perez
8e3073
Fixed remote name.
4 hours ago by Leonardo Perez
c6dfa8
Removed oauth prefix.
5 hours ago by Leonardo Perez
eec551
Test
5 hours ago by Leonardo Perez
e62c29
Added specific branch.
6 hours ago by Leonardo Perez
62aac9
Fixed origin rename.
6 hours ago by Leonardo Perez
e32f33
Added pull
8 hours ago by Leonardo Perez
c13700
Fixed url
8 hours ago by Leonardo Perez
24a99e
Added fetch
8 hours ago by Leonardo Perez
892e0d
Test
9 hours ago by Leonardo Perez
c77ff0
Fixed push.
9 hours ago by Leonardo Perez
c906c9
Added --config push.default matching.
9 hours ago by Leonardo Perez
a566b6
Update push statement.
10 hours ago by Leonardo Perez
e80aa6
Fixed checkout statement.
10 hours ago by Leonardo Perez
ff3bed
Another one
10 hours ago by Leonardo Perez
7881c1
Aother Test
11 hours ago by Leonardo Perez
5fdc4f
Another one!
11 hours ago by Leonardo Perez
4d6493
Test
11 hours ago by Leonardo Perez
c8c4ad
Yaml test
11 hours ago by Leonardo Perez
f099b5
Git Test
11 hours ago by Leonardo Perez
ef9934
Fixed user.name in config statement.
12 hours ago by Leonardo Perez
03769c
Removed commit statement from yaml.
12 hours ago by Leonardo Perez
4b5d84
Yaml Test
12 hours ago by Leonardo Perez
86060d
AppVeyor Updates.
12 hours ago by Leonardo Perez
a6f7cc
Initial code.
a day ago by Leonardo Perez
8de8b3
ADDED appveyor.yml
End of History
8de8b3
Leonardo Perez
62aac9
Leonardo Perez
9f49ed
Leonardo Perez
a6f7cc
Leonardo Perez
9f49ed
Leonardo Perez
cadfc3
Leonardo Perez
ab50d3
Leonardo Perez
9f49ed
Leonardo Perez
cadfc3
Leonardo Perez
9f49ed
Leonardo Perez
ab50d3
Leonardo Perez
9f49ed
Leonardo Perez
cadfc3
Leonardo Perez
9f49ed
Leonardo Perez
cadfc3
Leonardo Perez
a6f7cc
Leonardo Perez
9f49ed
Leonardo Perez
9d485f
Leonardo Perez
9f49ed
Leonardo Perez
cadfc3
Leonardo Perez
c4e057
Leonardo Perez
a6f7cc
Leonardo Perez
8de8b3
Leonardo Perez
9f49ed
Leonardo Perez
cadfc3
Leonardo Perez
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
version: 1.0.{build}
configuration: Debug
platform: Any CPU

before_build:
- cmd: nuget restore

build:
    project: HandyTools.sln
    verbosity: minimal
 
branches:
#Whitelist
    only:
        - master
       
environment:
    access_token:
        secure: ZQQ+zSR7as/HV8jDAzoCGcyckNahNpFZ97J+CNiHGZeQrkNWvLPyZWVBeaxzUvJv 

deploy:
- provider: S3
  access_key_id: AKIAJ5FDT2D2WPEZIUMA
  secret_access_key:
    secure: vQsAdbQEVkppDmyU+reBBPHL4zSKb7N2R1mHiO964YuWFvB0yOY3y3M5pTc+B++h
  region: us-east-1
  bucket: handytools
  artifacts: handytoolsweb
  set_public: true
- provider: S3
  access_key_id: AKIAJ5FDT2D2WPEZIUMA
  secret_access_key:
    secure: vQsAdbQEVkppDmyU+reBBPHL4zSKb7N2R1mHiO964YuWFvB0yOY3y3M5pTc+B++h
  region: us-east-1
  bucket: handytools-api
  artifacts: handytoolswebapi
  set_public: true
    
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.gatech.edu/gt-omscs-dbscd/CS6400Spring16Team60.git`n"
  - git config --global user.email "find.leonardo@gmail.com"
  - git config --global user.name "lperez42"
  - git remote rename origin upstream
  - git remote add gatech https://github.gatech.edu/gt-omscs-dbscd/CS6400Spring16Team60.git
  - git checkout master
  - git pull gatech master
  - git push gatech master
  
after_build:
  - ps: $root = Resolve-Path .\HandyTools.Web; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -DeploymentName handytoolsweb }
  - ps: $root = Resolve-Path .\HandyTools.Web.API; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -DeploymentName handytoolswebapi }

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: handytools-bot
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true