version: 1.0.{build}
configuration: Debug
platform: Any CPU
clone_folder: c:\projects\handytools

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node
  # install modules
  - cmd: cd c:\projects\handytools\HandyTools.Web
  - cmd: npm install
  - cmd: cd ..
  
# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

build:
  project: HandyTools.sln
  verbosity: normal
 
before_build:
  - cmd: nuget restore -SolutionDirectory c:\projects\handytools

branches:
#Whitelist
    only:
        - master

# Don't actually build.
# build: off
       
environment:
    access_token:
        secure: ZQQ+zSR7as/HV8jDAzoCGcyckNahNpFZ97J+CNiHGZeQrkNWvLPyZWVBeaxzUvJv

deploy:
- provider: S3
  access_key_id: AKIAJ5FDT2D2WPEZIUMA
  secret_access_key:
    secure: vQsAdbQEVkppDmyU+reBBPHL4zSKb7N2R1mHiO964YuWFvB0yOY3y3M5pTc+B++h
  region: us-east-1
  bucket: handytools  
  artifact: handytoolsweb
  set_public: false
- provider: S3
  access_key_id: AKIAJ5FDT2D2WPEZIUMA
  secret_access_key:
    secure: vQsAdbQEVkppDmyU+reBBPHL4zSKb7N2R1mHiO964YuWFvB0yOY3y3M5pTc+B++h
  region: us-east-1
  bucket: handytools-api
  artifact: handytoolsapi
  set_public: false
    
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.gatech.edu/gt-omscs-dbscd/CS6400Spring16Team60.git`n"
  - git config --global user.email "find.leonardo@gmail.com"
  - git config --global user.name "lperez42"
  - git remote rename origin upstream
  - git remote add gatech https://github.gatech.edu/gt-omscs-dbscd/CS6400Spring16Team60.git
  - git checkout master
  - git pull gatech master
  - git push gatech master
  
after_build:
  #- ps: $webroot = Resolve-Path .\HandyTools.Web; [IO.Directory]::GetFiles($webroot.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($webroot.Path.Length + 1) -DeploymentName handytoolsweb }
  #- ps: $apiroot = Resolve-Path .\HandyTools.Web.API; [IO.Directory]::GetFiles($apiroot.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($apiroot.Path.Length + 1) -DeploymentName handytoolsapi }
  - appveyor PushArtifact HandyTools.Web -DeploymentName handytoolsweb 
  - appveyor PushArtifact HandyTools.Web.API -DeploymentName handytoolsapi

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: handytools-bot
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true